imports:
  - { resource: 'testServices/*.yaml' }


services:
  _defaults:
    public: true

  Tests\OrganizationalFees\:
    resource: '../src/OrganizationalFees/tests/*'
    public: true

  Tests\OrganizationalFees\Domain\ArrangementFee\Model\ArrangementFeeTest:
    public: true

  Tests\OrganizationalFees\Application\Command\OrderCreate\OrderCreateCommandTest:
    public: true



  Shared\Infrastructure\Tests\Doctrine\DatabaseArrangerInterface: '@DatabaseArranger'

