services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  OrganizationalFees\Infrastructure\Repository\Domain\ArrangementFee\EventStory\EsArrangementFeeRepositoryPersistence:
    public: true

  OrganizationalFees\Infrastructure\Repository\Domain\Order\EventStore\EsOrderRepositoryPersistence:
    public: true

  OrganizationalFees\Infrastructure\Repository\Domain\Festival\EventStory\EsFestivalRepositoryPersistence:
    public: true

  OrganizationalFees\Infrastructure\Repository\Domain\PromoCode\EventStory\EsPromoCodeRepositoryPersistence:
    public: true

  OrganizationalFees\Infrastructure\Service\Template\TemplateService:
    public: true

  OrganizationalFees\Application\Command\Order\OrderApproved\OrderApprovedCommandHandler:
    public: true

  OrganizationalFees\Application\Command\Order\OrderCreate\OrderCreateCommandHandler:
    public: true

  OrganizationalFees\Application\Query\Order\GetOrderList\GetOrderListQueryHandler:
    public: true

  OrganizationalFees\Application\Query\PromoCode\FindPromoCode\FindPromoCodeQueryHandler:
    public: true

  OrganizationalFees\Application\Command\PromoCode\AddPromoCode\AddPromoCodeCommandHandler:
    public: true

  OrganizationalFees\Application\Query\ArrangementFee\GetArrangementFeeList\GetArrangementFeeListQueryHandler:
    public: true

  OrganizationalFees\Application\Query\ArrangementFee\GetArrangementFeeAllPriceList\GetArrangementFeeAllPriceListQueryHandler:
    public: true

  OrganizationalFees\Application\Command\ArrangementFee\AddArrangementFee\AddArrangementFeeCommandHandler:
    public: true

  OrganizationalFees\Application\Command\ArrangementFee\UpdatePrice\UpdatePriceCommandHandler:
    public: true

  OrganizationalFees\Application\Query\Festival\GetFestivalList\GetFestivalListQueryHandler:
    public: true

  OrganizationalFees\Application\Query\Festival\FindActiveFestival\FindActiveFestivalQueryHandler:
    public: true

  OrganizationalFees\Application\Command\Festival\FestivalCreate\FestivalCreateCommandHandler:
    public: true