POST http://localhost:{{PORT}}/festival/create
Content-Type: application/json

{
    "name": "test",
    "dateStart": "2024-01-01",
    "dateEnd": "2024-12-31",
    "mailTemplate": "textMail",
    "pdfTemplate": "textPdf"
}

###

GET http://localhost:{{PORT}}/festival/5702befb-b1d0-4658-9c48-4ef10f46afb0
Content-Type: application/json

###

PUT http://localhost:{{PORT}}/festival/edit/5702befb-b1d0-4658-9c48-4ef10f46afb0
Content-Type: application/json

{
  "name": "test2",
  "dateStart": "2024-01-20",
  "dateEnd": "2024-12-31",
  "mailTemplate": "textMail1",
  "pdfTemplate": "textPdf2"
}

###

DELETE http://localhost:{{PORT}}/festival/5702befb-b1d0-4658-9c48-4ef10f46afb0
Content-Type: application/json


