services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  Auth\:
    resource: '../../src/Auth/src/'

  Auth\Infrastructure\Projection\SecurityUser\Dbal\UserWasRegisteredProjection:
    tags: [ 'shared.domain.bus.projector.projection' ]

  Auth\Infrastructure\Projection\SecurityUser\Dbal\UserWasPasswordHashChangedProjection:
    tags: [ 'shared.domain.bus.projector.projection' ]